# Generated by Django 4.1.2 on 2022-10-27 00:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=180, verbose_name='Nome')),
                ('last_name', models.CharField(max_length=180, verbose_name='Sobrenome')),
                ('email', models.CharField(max_length=180, verbose_name='Email')),
                ('phone', models.CharField(max_length=180, verbose_name='Telefone')),
                ('cpf', models.CharField(max_length=180, verbose_name='CPF')),
                ('address', models.CharField(max_length=180, verbose_name='Endereço')),
                ('date_registration', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('Ativo', 'Active'), ('Desativado', 'Disabled')], max_length=180)),
            ],
        ),
    ]
